### PR TITLE
refactor(menu-button): added support for icons and bug fixes

### LINKED ISSUE #91: makeup-menu-button: add aria-haspopup if missing
I noticed the MIND pattern examples are missing aria-haspopup ,whereas the makeup example isn't. This is because Makeup example is adding the attribute in the base markup:

https://github.com/makeup/makeup-js/blob/master/docs/makeup-menu-button/index.html#L29

The `aria-haspopup` attribute should be added programmatically, if not already included in the base markup.

### LINKED ISSUE #134: makeup-menu-button: Add support for Icons
Add support for HTML other than just text during single-select. e.g. Add flag Icons for phone input

### PR DESCRIPTION
**Pull request by saiponnada**
Fixes #91, #134 

- Fixes setting `aria-haspopup` attribute to true programmatically.
- Added configuration option `buttonValueType` that takes one of these values [`text`, `icon`, `both`]
- For `buttonValueType` either `icon` or `both`, `iconSelector` option is used to select icon element.
- No changes were made to `makeup-menu`.
- Updated examples on both `makeup-menu` and `makeup-menu-button`. 

### makeup-menu
image

### makeup-menu-button
image

image

### CODE REVIEW

File: docs/makeup-menu/index.js [hunk 1]
```diff
@@ -12,11 +12,19 @@ import Menu from "../../packages/makeup-menu";
 const log = (e) => console.log(e.type, e.detail);
 
 window.onload = function () {
-  document.querySelectorAll(".menu").forEach(function (el, i) {
+  document.querySelectorAll(".menu:not(.menu-icon)").forEach(function (el, i) {
```
Comment (ArtBlue) [inline docs/makeup-menu/index.js:15]: Same thing here. Keep the same selector and conditionally add the additional `prop:value` pairs based on whether `.menu-icon` is present.

File: packages/makeup-menu-button/dist/cjs/index.js [hunk 2]
```diff
@@ -109,8 +115,12 @@ function _onMenuKeyDown(e) {
   }
 }
 function _onMenuItemSelect(e) {
-  if (this._buttonPrefix && e.detail.el.getAttribute("role") === "menuitemradio") {
-    this._buttonTextEl.innerText = "".concat(this._buttonPrefix, " ").concat(e.detail.el.innerText);
+  if (e.detail.el.getAttribute("role") === "menuitemradio") {
```
Comment (ArtBlue) [inline packages/makeup-menu-button/dist/cjs/index.js:118]: To make this more readable/maintainable, it's better to avoid nested conditionals. In this case, if you're looking for a specific type of `role`, just exit fast if it's the wrong role...

```js
if (e.detail.el.getAttribute("role") !== "menuitemradio") {
  return;
}
// then just continue with the rest of the logic in the current inner conditional. 
```

File: packages/makeup-menu-button/dist/mjs/index.js [hunk 3]
```diff
@@ -100,8 +106,12 @@ function _onMenuKeyDown(e) {
   }
 }
 function _onMenuItemSelect(e) {
-  if (this._buttonPrefix && e.detail.el.getAttribute("role") === "menuitemradio") {
-    this._buttonTextEl.innerText = `${this._buttonPrefix} ${e.detail.el.innerText}`;
+  if (e.detail.el.getAttribute("role") === "menuitemradio") {
```
Comment (ArtBlue) [inline packages/makeup-menu-button/dist/mjs/index.js:109]: Same comment as in the `cjs` file.

File: packages/makeup-menu-button/src/index.js [hunk 4]
```diff
@@ -117,8 +121,14 @@ function _onMenuKeyDown(e) {
 }
 
 function _onMenuItemSelect(e) {
-  if (this._buttonPrefix && e.detail.el.getAttribute("role") === "menuitemradio") {
-    this._buttonTextEl.innerText = `${this._buttonPrefix} ${e.detail.el.innerText}`;
+  if (e.detail.el.getAttribute("role") === "menuitemradio") {
```
Comment (ArtBlue) [inline packages/makeup-menu-button/src/index.js:124]: Sorry, the other comments were on the files in the `dist` folder, but the same would apply here.

**Review by ArtBlue — CHANGES_REQUESTED** [review]

File: packages/makeup-menu-button/src/index.js (hunk 4 above)
Comment (saiponnada) [reply packages/makeup-menu-button/src/index.js:124]: Unfortunately, we cannot return early as weather the condition is met or not, we still need to execute L134 here.

File: packages/makeup-menu-button/dist/mjs/index.js (hunk 3 above)
Comment (saiponnada) [reply packages/makeup-menu-button/dist/mjs/index.js:109]: Part of dist folder.

File: packages/makeup-menu-button/dist/cjs/index.js (hunk 2 above)
Comment (saiponnada) [reply packages/makeup-menu-button/dist/cjs/index.js:118]: Part of dist folder.

File: packages/makeup-menu-button/src/index.js (hunk 4 above)
Comment (ArtBlue) [reply packages/makeup-menu-button/src/index.js:124]: `const` should typically be defined at the top of functions, so just move that up to the top and you should be able to do a return.

File: packages/makeup-menu/src/index.js [hunk 5]
```diff
@@ -181,7 +183,7 @@ function _selectMenuItemCheckbox(widgetEl, menuItemEl) {
   }
 }
 
-function _selectMenuItemRadio(widgetEl, menuItemEl) {
+function _selectMenuItemRadio(widgetEl, menuItemEl, options) {
   if (menuItemEl.getAttribute("aria-disabled") !== "true") {
```
Comment (ArtBlue) [inline packages/makeup-menu/src/index.js:187]: I realize this is not part of this PR, but while we're at it, we should change this too. Lengthy and nested conditional blocks should be avoided when possible. It improves readability and adds simplicity. 

So, this would turn into this:

```js
// if menu item element is disabled, exit function
if (menuItemEl.getAttribute("aria-disabled") === "true") {
  return;
}
```

**Review by ArtBlue — CHANGES_REQUESTED** [review]

File: docs/makeup-menu-button/index.html [hunk 6]
```diff
@@ -189,6 +189,61 @@ <h2 id="menu-button-2C">Single-Select Menu Button with Stateful Label</h2>
 
         <hr />
 
+        <h2 id="menu-button-2D">Single-Select Menu Button with Icons</h2>
+
+        <span class="menu-button menu-button-with-icon">
+          <button class="btn" type="button">
+            <span class="btn__text">
+              <svg class="icon icon--amex-18-colored" focusable="false" height="18" width="30" aria-hidden="true">
+                <use xlink:href="../icons.svg#icon-amex-18-colored"></use>
```
[the remark this answers is not in the document]
Comment (saiponnada) [reply docs/makeup-menu-button/index.html:198]: Fixed in this [PR](https://github.com/makeup/makeup-js/pull/137).

File: packages/makeup-menu-button/src/index.js [hunk 7]
```diff
@@ -117,14 +121,22 @@ function _onMenuKeyDown(e) {
...
   }, 150);
+
+  if (e.detail.el.getAttribute("role") !== "menuitemradio") {
+    return;
+  }
+
+  const valueSelector = e.detail.el.querySelector(this._options.valueSelector);
+  if (valueSelector) {
+    const valueType = this._options.valueTypeHTML ? "innerHTML" : "innerText";
+    this._buttonTextEl[valueType] = valueSelector[valueType];
```
Comment (LuLaValva) [inline packages/makeup-menu-button/src/index.js:138]: This disregards any prefix that might exist, is it an anti-pattern to use both a prefix and `valueTypeHTML`?

**Review by LuLaValva — COMMENTED** [review]
Looks awesome! Just one quick comment.

File: packages/makeup-menu-button/src/index.js (hunk 7 above)
Comment (saiponnada) [reply packages/makeup-menu-button/src/index.js:138]: Yeah, I assumed when you have a selector, you have more ability to include all the elements in it. Adding a prefix is unnecessary but I don't have a strong preference for this.

Comment (LuLaValva) [reply packages/makeup-menu-button/src/index.js:138]: Ok, if you want to keep it this way then it should be documented somewhere that you can't use both prefix and valueTypeHTML

Comment (saiponnada) [reply packages/makeup-menu-button/src/index.js]: Refactored code to consider both prefixed text and Icon.
